exclude: ['README.md']

theme: jekyll-theme-primer

title: learnlatex.org
description: Learn LaTeX online

logo: learnlatex.png

plugins:
  - jekyll-sitemap

latex: "<span>L<span style='font-variant: small-caps; vertical-align:.35ex;margin-left:-.15em;margin-right:-.05em;'>a</span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
tex: "<span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"

langs:
   - en
   - de
   - fr
   - pt
   - ja
   - vi
   - zh

